### ISSUE TITLE
Building on Apple Silicon (M1/M2)

### ISSUE THREAD

**Issue by janblumenkamp** [dora-rs/dora#329]
**Describe the bug**
I am trying to build dora on Apple Silicon. Building succeeds, but running dora fails due to a missing Python library.

**To Reproduce**
I installed cargo and maturin and followed the installation instructions to build from source:
```
git clone https://github.com/dora-rs/dora.git
cd dora
cargo build --release --all 
PATH=$PATH:$(pwd)/target/release
alias dora='dora-cli'

cd apis/python/node
maturin develop --release
cd ../../..
```
Everything runs successfully, but when trying to run `dora`, I get the following error:
```
➜  dora git:(main) dora
dyld[15934]: Library not loaded: '@rpath/libpython3.10.dylib'
  Referenced from: '/Users/jan/Documents/Projects/dora/target/release/dora-cli'
  Reason: tried: '/usr/local/lib/libpython3.10.dylib' (no such file), '/usr/lib/libpython3.10.dylib' (no such file)
[1]    15934 abort      dora-cli
```

**Expected behavior**
I expect dora to run successfully, instead it fails due to a missing python library.

**Environments (please complete the following information):**
 - System info: Apple Macbook Air M2: `Darwin Jans-MacBook-Air-859.local 21.6.0 Darwin Kernel Version 21.6.0: Sat Jun 18 17:07:28 PDT 2022; root:xnu-8020.140.41~1/RELEASE_ARM64_T8110 arm64`
 - Dora version: 89bae20

**Additional context**
N/A

**Comment by haixuanTao** [comment]
That is weird indeed,

Can you try building those package separately, as follows:

```bash
cargo build -p dora-coordinator --release
cargo build -p dora-daemon --release
cargo build -p dora-cli --release
```

I don't have an Apple M1 unfortunately.

The error you see comes from, unexpected linking of the python dynamic library.

**Comment by janblumenkamp** [comment]
I was able to resolve this by simply deactivating my base conda env!

**Comment by janblumenkamp** [comment]
Actually, there seems to be another problem. The examples `c-dataflow`, `rust-dataflow` and `cxx-dataflow` compile and run successfully, but for `python-dataflow` I get the following error when building.

<details>

<summary>Error for building python-dataflow</summary>

```
➜  dora git:(main) cargo run --example python-dataflow
warning: unused variable: `dataflow_descriptor`
  --> binaries/runtime/src/operator/mod.rs:22:5
   |
22 |     dataflow_descriptor: &Descriptor,
   |     ^^^^^^^^^^^^^^^^^^^ help: if this is intentional, prefix it with an underscore: `_dataflow_descriptor`
   |
   = note: `#[warn(unused_variables)]` on by default

warning: `dora-runtime` (lib) generated 1 warning (run `cargo fix --lib -p dora-runtime` to apply 1 suggestion)
    Finished dev [unoptimized + debuginfo] target(s) in 0.28s
     Running `target/debug/examples/python-dataflow`
warning: unused variable: `dataflow_descriptor`
  --> binaries/runtime/src/operator/mod.rs:22:5
   |
22 |     dataflow_descriptor: &Descriptor,
   |     ^^^^^^^^^^^^^^^^^^^ help: if this is intentional, prefix it with an underscore: `_dataflow_descriptor`
   |
   = note: `#[warn(unused_variables)]` on by default

warning: `dora-runtime` (lib) generated 1 warning (run `cargo fix --lib -p dora-runtime` to apply 1 suggestion)
    Finished dev [unoptimized + debuginfo] target(s) in 0.15s
Collecting patchelf
  Using cached patchelf-0.17.2.1.tar.gz (167 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: patchelf
  Building wheel for patchelf (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for patchelf (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [195 lines of output]
      
      
      --------------------------------------------------------------------------------
      -- Trying 'Ninja' generator
      --------------------------------
      ---------------------------
      ----------------------
      -----------------
      ------------
      -------
      --
      CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
        Compatibility with CMake < 3.5 will be removed from a future version of
        CMake.
      
        Update the VERSION argument <min> value or use a ...<max> suffix to tell
        CMake that the project does not need compatibility with older versions.
      
      Not searching for unused variables given on the command line.
      
      CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
      -- Configuring incomplete, errors occurred!
      --
      -------
      ------------
      -----------------
      ----------------------
      ---------------------------
      --------------------------------
      -- Trying 'Ninja' generator - failure
      --------------------------------------------------------------------------------
      
      
      
      --------------------------------------------------------------------------------
      -- Trying 'Unix Makefiles' generator
      --------------------------------
      ---------------------------
      ----------------------
      -----------------
      ------------
      -------
      --
      CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
        Compatibility with CMake < 3.5 will be removed from a future version of
        CMake.
      
        Update the VERSION argument <min> value or use a ...<max> suffix to tell
        CMake that the project does not need compatibility with older versions.
      
      Not searching for unused variables given on the command line.
      
      -- The C compiler identification is AppleClang 13.1.6.13160021
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- The CXX compiler identification is AppleClang 13.1.6.13160021
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      -- Configuring done (0.3s)
      -- Generating done (0.0s)
      -- Build files have been written to: /private/var/folders/rb/ctnwr_1n3cj4_xg5l4l_2_0h0000gn/T/pip-install-ny3bj5l9/patchelf_88047e72e7e74d8eb6e0b9c208f7702c/_cmake_test_compile/build
      --
      -------
      ------------
      -----------------
      ----------------------
      ---------------------------
      --------------------------------
      -- Trying 'Unix Makefiles' generator - success
      --------------------------------------------------------------------------------
      
      Configuring Project
        Working directory:
          /private/var/folders/rb/ctnwr_1n3cj4_xg5l4l_2_0h0000gn/T/pip-install-ny3bj5l9/patchelf_88047e72e7e74d8eb6e0b9c208f7702c/_skbuild/macosx-12.0-arm64-3.11/cmake-build
        Command:
          /opt/homebrew/bin/cmake /private/var/folders/rb/ctnwr_1n3cj4_xg5l4l_2_0h0000gn/T/pip-install-ny3bj5l9/patchelf_88047e72e7e74d8eb6e0b9c208f7702c -G 'Unix Makefiles' --no-warn-unused-cli -DCMAKE_INSTALL_PREFIX:PATH=/private/var/folders/rb/ctnwr_1n3cj4_xg5l4l_2_0h0000gn/T/pip-install-ny3bj5l9/patchelf_88047e72e7e74d8eb6e0b9c208f7702c/_skbuild/macosx-12.0-arm64-3.11/cmake-install -DPYTHON_VERSION_STRING:STRING=3.11.4 -DSKBUILD:INTERNAL=TRUE -DCMAKE_MODULE_PATH:PATH=/private/var/folders/rb/ctnwr_1n3cj4_xg5l4l_2_0h0000gn/T/pip-build-env-_8fcx59n/overlay/lib/python3.11/site-packages/skbuild/resources/cmake -DPYTHON_EXECUTABLE:PATH=/Users/jan/Documents/Projects/dora/examples/python-dataflow/.env/bin/python3.11 -DPYTHON_INCLUDE_DIR:PATH=/opt/homebrew/opt/python@3.11/Frameworks/Python.framework/Versions/3.11/include/python3.11 -DPYTHON_LIBRARY:PATH=/opt/homebrew/opt/python@3.11/Frameworks/Python.framework/Versions/3.11/lib/libpython3.11.dylib -DPython_EXECUTABLE:PATH=/Users/jan/Documents/Projects/dora/examples/python-dataflow/.env/bin/python3.11 -DPython_ROOT_DIR:PATH=/Users/jan/Documents/Projects/dora/examples/python-dataflow/.env -DPython_FIND_REGISTRY:STRING=NEVER -DPython_INCLUDE_DIR:PATH=/opt/homebrew/opt/python@3.11/Frameworks/Python.framework/Versions/3.11/include/python3.11 -DPython3_EXECUTABLE:PATH=/Users/jan/Documents/Projects/dora/examples/python-dataflow/.env/bin/python3.11 -DPython3_ROOT_DIR:PATH=/Users/jan/Documents/Projects/dora/examples/python-dataflow/.env -DPython3_FIND_REGISTRY:STRING=NEVER -DPython3_INCLUDE_DIR:PATH=/opt/homebrew/opt/python@3.11/Frameworks/Python.framework/Versions/3.11/include/python3.11 -DCMAKE_OSX_DEPLOYMENT_TARGET:STRING=12.0 -DCMAKE_OSX_ARCHITECTURES:STRING=arm64 -DCMAKE_BUILD_TYPE:STRING=Release
      
      Not searching for unused variables given on the command line.
      -- The C compiler identification is AppleClang 13.1.6.13160021
      -- The CXX compiler identification is AppleClang 13.1.6.13160021
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      -- Configuring done (0.3s)
      -- Generating done (0.0s)
      -- Build files have been written to: /private/var/folders/rb/ctnwr_1n3cj4_xg5l4l_2_0h0000gn/T/pip-install-ny3bj5l9/patchelf_88047e72e7e74d8eb6e0b9c208f7702c/_skbuild/macosx-12.0-arm64-3.11/cmake-build
      [ 11%] Creating directories for 'build_patchelf'
      [ 22%] No download step for 'build_patchelf'
      [ 33%] No update step for 'build_patchelf'
      [ 44%] Performing patch step for 'build_patchelf'
      autoreconf: export WARNINGS=all
      autoreconf: Entering directory '.'
      autoreconf: configure.ac: not using Gettext
      autoreconf: running: aclocal --force
      autoreconf: configure.ac: tracing
      autoreconf: configure.ac: creating directory build-aux
      autoreconf: configure.ac: not using Libtool
      autoreconf: configure.ac: not using Intltool
      autoreconf: configure.ac: not using Gtkdoc
      autoreconf: running: /opt/homebrew/Cellar/autoconf/2.71/bin/autoconf --force
      autoreconf: configure.ac: not using Autoheader
      autoreconf: running: automake --add-missing --copy --force-missing
      configure.ac:14: installing 'build-aux/compile'
      configure.ac:5: installing 'build-aux/install-sh'
      configure.ac:5: installing 'build-aux/missing'
      src/Makefile.am: installing 'build-aux/depcomp'
      parallel-tests: installing 'build-aux/test-driver'
      autoreconf: Leaving directory '.'
      [ 55%] Performing configure step for 'build_patchelf'
      checking for a BSD-compatible install... /usr/bin/install -c
      checking whether build environment is sane... yes
      checking for a race-free mkdir -p... ./build-aux/install-sh -c -d
      checking for gawk... no
      checking for mawk... no
      checking for nawk... no
      checking for awk... awk
      checking whether make sets $(MAKE)... yes
      checking whether make supports nested variables... yes
      checking for strip... strip
      checking for objdump... objdump
      checking for objcopy... no
      checking for readelf... no
      checking whether make supports the include directive... yes (GNU style)
      checking for gcc... gcc
      checking whether the C compiler works... yes
      checking for C compiler default output file name... a.out
      checking for suffix of executables...
      checking whether we are cross compiling... no
      checking for suffix of object files... o
      checking whether the compiler supports GNU C... yes
      checking whether gcc accepts -g... yes
      checking for gcc option to enable C11 features... none needed
      checking whether gcc understands -c and -o together... yes
      checking dependency style of gcc... gcc3
      checking for g++... g++
      checking whether the compiler supports GNU C++... yes
      checking whether g++ accepts -g... yes
      checking for g++ option to enable C++11 features... none needed
      checking dependency style of g++... gcc3
      checking dependency style of gcc... gcc3
      checking whether g++ supports C++17 features with -std=c++17... yes
      checking that generated files are newer than configure... done
      configure: creating ./config.status
      config.status: creating Makefile
      config.status: creating src/Makefile
      config.status: creating tests/Makefile
      config.status: creating patchelf.spec
      config.status: executing depfiles commands
      [ 66%] Performing build step for 'build_patchelf'
      Making check in src
      Making check in tests
      clang: warning: argument unused during compilation: '-pie' [-Wunused-command-line-argument]
      clang: warning: argument unused during compilation: '-pie' [-Wunused-command-line-argument]
      foo.c:5:65: error: argument to 'section' attribute is not valid for this target: mach-o section specifier requires a segment and section separated by a comma
      const char __invoke_dynamic_linker__[] __attribute__ ((section (".interp"))) = "/foo/bar";
                                                                      ^
      1 error generated.
      make[5]: *** [foo.o] Error 1
      make[4]: *** [check-am] Error 2
      make[3]: *** [check-recursive] Error 1
      make[2]: *** [build_patchelf-prefix/src/build_patchelf-stamp/build_patchelf-build] Error 2
      make[1]: *** [CMakeFiles/build_patchelf.dir/all] Error 2
      make: *** [all] Error 2
      Traceback (most recent call last):
        File "/private/var/folders/rb/ctnwr_1n3cj4_xg5l4l_2_0h0000gn/T/pip-build-env-_8fcx59n/overlay/lib/python3.11/site-packages/skbuild/setuptools_wrap.py", line 674, in setup
          cmkr.make(make_args, install_target=cmake_install_target, env=env)
        File "/private/var/folders/rb/ctnwr_1n3cj4_xg5l4l_2_0h0000gn/T/pip-build-env-_8fcx59n/overlay/lib/python3.11/site-packages/skbuild/cmaker.py", line 697, in make
          self.make_impl(clargs=clargs, config=config, source_dir=source_dir, install_target=install_target, env=env)
        File "/private/var/folders/rb/ctnwr_1n3cj4_xg5l4l_2_0h0000gn/T/pip-build-env-_8fcx59n/overlay/lib/python3.11/site-packages/skbuild/cmaker.py", line 742, in make_impl
          raise SKBuildError(msg)
      
      An error occurred while building with CMake.
        Command:
          /opt/homebrew/bin/cmake --build . --target install --config Release --
        Install target:
          install
        Source directory:
          /private/var/folders/rb/ctnwr_1n3cj4_xg5l4l_2_0h0000gn/T/pip-install-ny3bj5l9/patchelf_88047e72e7e74d8eb6e0b9c208f7702c
        Working directory:
          /private/var/folders/rb/ctnwr_1n3cj4_xg5l4l_2_0h0000gn/T/pip-install-ny3bj5l9/patchelf_88047e72e7e74d8eb6e0b9c208f7702c/_skbuild/macosx-12.0-arm64-3.11/cmake-build
      Please check the install target is valid and see CMake's output for more information.
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for patchelf
Failed to build patchelf
ERROR: Could not build wheels for patchelf, which is required to install pyproject.toml-based projects
Error: failed to run python example.

Location:
    examples/python-dataflow/run.rs:34:9
```

</details>

**Comment by haixuanTao** [comment]
Thanks for the detailed bug report.
I have removed `patchelf` that should not be necessary anymore. I have also added `macos` in our CI to make sure that the python example run on `macos`.
Do you mind checking out the branch `removing-patchelf` with:
```bash
git pull
git checkout -b removing-patchelf
```
And see if your issue is fixed?

**Comment by janblumenkamp** [comment]
Yes, this works! Thank you!
