### ISSUE TITLE
dora can't start with mineflyer(windows)

### ISSUE THREAD

**Issue by Felixhuangsiling** [dora-rs/dora#395]
**Describe the bug**
start dora using mineflyer on windows 11 gave this bug.
```
2023-12-19T14:01:16.978348Z ERROR dora_daemon::spawn: e4d1615d-aa0b-4cd2-b246-b73f9b0eb2b5/bot: 
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.496.0_x64__qbz5n2kfra8p0\Lib\threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.496.0_x64__qbz5n2kfra8p0\Lib\threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\fg200\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\javascript\connection.py", line 173, in com_io
    item = readComItem(proc.stderr)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\fg200\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\javascript\connection.py", line 94, in readComItem
    print("[JSE]", line)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.496.0_x64__qbz5n2kfra8p0\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f40d' in position 1: character maps to <undefined>

    at C:\Users\fg200\.cargo\registry\src\index.crates.io-6f17d22bba15001f\dora-daemon-0.3.0\src\spawn.rs:274

```
**To Reproduce**
1. Dora start daemon: `dora-cli up` 
2. Start a new dataflow: `dora-cli start dataflow.yaml`

**Expected behavior**
dora runs

**Environments (please complete the following information):**
 - System info: Windows 11
 - Dora version: 0.3.0

**Comment by haixuanTao** [comment]
This issue was fixed with https://stackoverflow.com/questions/27092833/unicodeencodeerror-charmap-codec-cant-encode-characters

Specifically:
```python
import sys
sys.stdin.reconfigure(encoding='utf-8')
sys.stdout.reconfigure(encoding='utf-8')

```
